/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-12 08:08:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.porder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class create_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1586748538176L));
    _jspx_dependants.put("jar:file:/C:/ai6/ws__frame/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team4_v2s4m3c/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>♥SKINFIT♥</title>\r\n");
      out.write("  \r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/javascript/script.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("    .table_sty {\r\n");
      out.write("      border-collapse: collapse;   \r\n");
      out.write("      border-top: 3px solid gray;\r\n");
      out.write("      border-bottom: 1px solid gray;\r\n");
      out.write("    }\r\n");
      out.write("    .table_sty tr{\r\n");
      out.write("      border-top: 1px solid gray;\r\n");
      out.write("      border-bottom: 1px solid gray;\r\n");
      out.write("    }\r\n");
      out.write("    .table_sty th{\r\n");
      out.write("      border-right: 1px solid gray;\r\n");
      out.write("      padding-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .table_sty td{\r\n");
      out.write("      padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table_sty2{\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("      border: 1px solid gray;\r\n");
      out.write("      border-top: 2px solid black;\r\n");
      out.write("      border-spacing: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table_sty2 tr{\r\n");
      out.write("      margin: 20px;\r\n");
      out.write("      border-bottom: 1px solid gray;\r\n");
      out.write("    }\r\n");
      out.write("    .table_sty2 th{\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table_sty2 td{\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn_dflt1{\r\n");
      out.write("      width:200px; height:40px; line-height:40px; \r\n");
      out.write("      margin:15px auto; \r\n");
      out.write("      text-align:center; cursor: pointer; color:#333; transition:all 0.9s, color 0.3;\r\n");
      out.write("      border: none;\r\n");
      out.write("    }\r\n");
      out.write("    .btn_dflt1:hover{\r\n");
      out.write("      box-shadow:200px 0 0 0 rgba(0,0,0,0.5) inset;\r\n");
      out.write("      border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn_dflt1:active{\r\n");
      out.write("      /*  */\r\n");
      out.write("      box-shadow:200px 0 0 0 rgba(0,0,0,0) inset;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"showImage()\">\r\n");
      out.write("  <!-- jsp:include -> jsp가 처리되어 처리 결과가 HTML로 변경되어 메인 페이지에 포함 -->\r\n");
      out.write("  <!-- root를 사용하기 위해 cset을 다시 선언해야 한다. -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/menu/top.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- 주문/결제창 시작 -->\r\n");
      out.write("  <div style=\"width: 70%; margin: 20px auto;\">\r\n");
      out.write("    <div>\r\n");
      out.write("      <h2 style=\"display: inline;\">주문/결제</h2>\r\n");
      out.write("      <span style=\"float: right;\">1. 장바구니 ＞ <strong style=\"background-color: #ffffff;\">2. 주문/결제</strong> ＞ 3. 주문 완료</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");

      int memno = 1;
      request.setAttribute("memno", memno);
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- 구매자 정보 시작 -->\r\n");
      out.write("    <div style=\"margin: 20px auto;\">\r\n");
      out.write("      <table class=\"table_sty\" style='width: 100%;'>\r\n");
      out.write("        <caption style=\"text-align:left;\"><h3>구매자 정보</h3></caption>\r\n");
      out.write("        <colgroup>\r\n");
      out.write("          <col style=\"width: 10%;\"></col>\r\n");
      out.write("          <col style=\"width: 90%;\"></col>\r\n");
      out.write("        </colgroup>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <tbody>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>이름</th>\r\n");
      out.write("            <td style='text-align: left;'>왕눈이</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>이메일</th>\r\n");
      out.write("            <td style='text-align: left;'>wangnuni@gmail.com</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>휴대폰 번호</th>\r\n");
      out.write("            <td style='text-align: left;'>\r\n");
      out.write("              <input type=\"text\" value=\"010-5555-5555\" readonly=\"readonly\">\r\n");
      out.write("              <button type=\"button\">인증받기</button><br>\r\n");
      out.write("              * 거래기록 보존을 위해 본인확인 후 구매가 가능. (첫구매 1회만)<br>\r\n");
      out.write("              * 인증 번호를 못 받았다면, 1577-7011 번호 차단 및 스팸 설정을 확인해 주세요.<br>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 구매자 정보 종료 -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 배송 정보 시작 -->\r\n");
      out.write("    <div style=\"margin: 20px auto;\">\r\n");
      out.write("      <table class=\"table_sty\" style='width: 100%;'>\r\n");
      out.write("        <caption style=\"text-align:left;\"><h3>배송 정보</h3></caption>\r\n");
      out.write("        <colgroup>\r\n");
      out.write("          <col style=\"width: 10%;\"></col>\r\n");
      out.write("          <col style=\"width: 90%;\"></col>\r\n");
      out.write("        </colgroup>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <tbody>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>받는 사람</th>\r\n");
      out.write("            <td style='text-align: left;'>왕눈이</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>휴대폰 번호</th>\r\n");
      out.write("            <td style='text-align: left;'><input type=\"text\" value=\"010-5555-5555\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>배송 주소</th>\r\n");
      out.write("            <td style='text-align: left;'>\r\n");
      out.write("              <input type=\"text\" id='porder_zip_code' placeholder=\"우편번호\" value=\"1111\" style=\"width: 200px;\" required=\"required\"><br>\r\n");
      out.write("              <input type=\"text\" id='porder_address' placeholder=\"상세주소\" value=\"서울특별시 강남구\" style=\"width: 500px;\" required=\"required\">\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th style='text-align: right;'>배송 요청 사항</th>\r\n");
      out.write("            <td style='text-align: left;'>\r\n");
      out.write("              <textarea id='porder_delivery_request' rows=\"3\" style=\"width: 500px;\">문 앞에 두고 가세요</textarea>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 배송 정보 종료 -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 주문 상품 시작 -->\r\n");
      out.write("    <div style=\"margin: 60px auto; width:100%; border: 1px solid black;\">\r\n");
      out.write("      <div style=\"margin: 20px auto; width: 95%; border-bottom: 1px solid gray\"><h3>주문 상품</h3></div>\r\n");
      out.write("      <div style=\"margin: 20px auto; width: 95%;\">\r\n");
      out.write("        <table style='width: 100%;'>\r\n");
      out.write("          <colgroup>\r\n");
      out.write("            <col style=\"width: 10%;\"></col>\r\n");
      out.write("            <col style=\"width: 50%;\"></col>\r\n");
      out.write("            <col style=\"width: 20%;\"></col>\r\n");
      out.write("            <col style=\"width: 20%;\"></col>\r\n");
      out.write("          </colgroup>\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          <tbody>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>  \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 주문 상품 종료 -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 결제 정보 시작  -->\r\n");
      out.write("    <div style=\"margin: 20px auto; border: 1px solid gray;\">\r\n");
      out.write("      <h3 style=\"margin: 20px 20px;\">결제 정보</h3>\r\n");
      out.write("      <ul style=\"list-style: none; margin: 20px 30px 0 30px; padding:0 0 10px 0; border-bottom: 2px solid gray;\">\r\n");
      out.write("        <li style=\"text-align: right;\"><span style=\"float: left;\">판매가총액</span><span >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_price_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</span></li>\r\n");
      out.write("        <li style=\"text-align: right;\"><span style=\"float: left;\">할인총액</span><span >-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</span></li>\r\n");
      out.write("        <li style=\"text-align: right;\"><span style=\"float: left;\">쿠폰할인</span><span>-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.coupon_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</span></li>\r\n");
      out.write("        <li style=\"text-align: right;\"><span style=\"float: left;\">배송비</span><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.delivery_fee }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</span></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div style=\"padding: 5px 30px; text-align: right; border-bottom: 1px solid gray;\">\r\n");
      out.write("        <span  style=\"float: left; margin-top: 10px;\"><strong>최종 결제 금액</strong></span>\r\n");
      out.write("        <span  style=\"font-weight: bold; color: red; font-size: 26px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.payment_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"padding: 10px 20px; border-bottom: 1px solid gray;\">\r\n");
      out.write("        <div style=\"font-weight: bold; margin: 5px;\">결제 방법</div>\r\n");
      out.write("        <label><input type=\"radio\" name='method' value='kakaopay'>카카오페이</label>\r\n");
      out.write("        <label><input type=\"radio\" name='method' value='naverpay'>네이버페이</label>\r\n");
      out.write("        <label><input type=\"radio\" name='method' value='insis'>이니시스</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"padding: 10px 20px;\">\r\n");
      out.write("        <label><input type=\"checkbox\" name='order_list_agreement' value='yes'>주문내역확인 동의(필수)</label>\r\n");
      out.write("        <div style=\"font-size: 12px; margin: 0 20px;\">\r\n");
      out.write("          주문할 상품의 상품명, 가격, 배송정보 등을 최종 확인하였으며, 구매에 동의하십니까?\r\n");
      out.write("          (전자상거래법 제 8조 2항)\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 결제 정보 종료  -->\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"margin: 20px auto; text-align: center;\">\r\n");
      out.write("      <button type=\"button\" class=\"btn_dflt1\" style=\"width: 100px; height: 60px; border-radius: 5%;\" onclick=\"history.back();\">장바구니 가기</button>\r\n");
      out.write("      <button type=\"button\" id=\"btn_buy\" class=\"btn_dflt1\" style=\"width: 100px; height: 60px; border-radius: 5%;\">결제하기</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- 주문/결제창 종료 -->\r\n");
      out.write("   \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/menu/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("      $('#btn_buy').on('click', create_pay)\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // json, jsonArray 형태로 정보 전송 -> 이대로 결제 처리\r\n");
      out.write("    function create_pay(){\r\n");
      out.write("      // ajax로 처리\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      var porderJSON={\r\n");
      out.write("                              'memno':'1',\r\n");
      out.write("                              'item_price_sum':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_price_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("                              'item_discount_sum':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("                              'coupon_discount_sum':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.coupon_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("                              'delivery_fee':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.delivery_fee }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("                              'payment_price':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.payment_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("                              //'porder_status':'1',\r\n");
      out.write("                              'porder_zip_code': $('#porder_zip_code').val(),\r\n");
      out.write("                              'porder_address':$('#porder_address').val(),\r\n");
      out.write("                              'porder_delivery_request':$('#porder_delivery_request').html()\r\n");
      out.write("                             };\r\n");
      out.write("      \r\n");
      out.write("      var porder_detailArr = [];\r\n");
      out.write("      \r\n");
      out.write("      // 상품 개수 만큼 순회      \r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      // JSON형식의 String 변환은 단 한번 해준다, JSON 내부의 JSON은 모두 String 형태로 직접 변환해줘야 한다.\r\n");
      out.write("      var params = {'porderJSONString':JSON.stringify(porderJSON), 'porder_detailArrString':JSON.stringify(porder_detailArr)};\r\n");
      out.write("      \r\n");
      out.write("      //alert(params);\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("        url: './create.do',\r\n");
      out.write("        type: 'post',\r\n");
      out.write("        //traditional: true, // json 배열 전송??\r\n");
      out.write("        cache: false, // 응답 결과 임시 저장 취소\r\n");
      out.write("        async: false,  // false: 동기 통신 -> 주문이 중복으로 들어가는 것을 방지, 절차적으로 처리\r\n");
      out.write("        dataType: 'json', // 응답 형식: json, html, xml...\r\n");
      out.write("        data: params,      // 데이터\r\n");
      out.write("        success: function(rdata) { // 서버로부터 성공적으로 응답이 온경우\r\n");
      out.write("          //var msg = \"\";\r\n");
      out.write("          //alert(rdata.result);\r\n");
      out.write("          if(rdata.result == \"fully success\"){\r\n");
      out.write("            alert(\"결과 페이지 이동\");\r\n");
      out.write("            location.href=\"./complete.do?cnt=1\";\r\n");
      out.write("          } else{\r\n");
      out.write("            alert(\"결제 오류\");\r\n");
      out.write("            \r\n");
      out.write("          }\r\n");
      out.write("          /* if (rdata.result) { // 주문 입력, 주문상세 입력 처리 성공\r\n");
      out.write("            // frm.submit();\r\n");
      out.write("          } else {  // 결제 오류\r\n");
      out.write("            \r\n");
      out.write("          } */\r\n");
      out.write("        },\r\n");
      out.write("        // Ajax 통신 에러, 응답 코드가 200이 아닌경우, dataType이 다른경우 \r\n");
      out.write("        error: function(request, status, error) { // callback 함수\r\n");
      out.write("          var msg = 'ERROR<br><br>';\r\n");
      out.write("          msg += '<strong>request.status</strong><br>'+request.status + '<hr>';\r\n");
      out.write("          msg += '<strong>error</strong><br>'+error + '<hr>';\r\n");
      out.write("          console.log(msg);\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function create_porder(){\r\n");
      out.write("      var form = document.createElement(\"form\");\r\n");
      out.write("      form.action=\"./create.do\";\r\n");
      out.write("      form.method=\"post\";\r\n");
      out.write("      $(\"body\").append(form);\r\n");
      out.write("      \r\n");
      out.write("      //alert(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("      //return;\r\n");
      out.write("      \r\n");
      out.write("      //EL 값을 넣음\r\n");
      out.write("      create_hidden(\"memno\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form); \r\n");
      out.write("      \r\n");
      out.write("      create_hidden(\"item_price_sum\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_price_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form);\r\n");
      out.write("      create_hidden(\"item_discount_sum\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.item_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form);\r\n");
      out.write("      create_hidden(\"coupon_discount_sum\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.coupon_discount_sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form);\r\n");
      out.write("      create_hidden(\"delivery_fee\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.delivery_fee }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form);\r\n");
      out.write("      create_hidden(\"payment_price\", ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${porderVO.payment_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", form);\r\n");
      out.write("      \r\n");
      out.write("      create_hidden(\"porder_status\", \"R\", form);\r\n");
      out.write("      \r\n");
      out.write("      if($('#porder_zip_code').val() == \"\"){\r\n");
      out.write("        $('#porder_zip_code').focus();\r\n");
      out.write("        alert(\"우편번호를 입력해주세요.\");\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("      create_hidden(\"porder_zip_code\", $('#porder_zip_code').val(), form);\r\n");
      out.write("      \r\n");
      out.write("      if($('#porder_address').val() == \"\"){\r\n");
      out.write("        $('#porder_address').focus();\r\n");
      out.write("        alert(\"상세주소를 입력해주세요\");\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("      create_hidden(\"porder_address\", $('#porder_address').val(), form);\r\n");
      out.write("      \r\n");
      out.write("      create_hidden(\"porder_delivery_request\", $('#porder_delivery_request').html(), form);\r\n");
      out.write("      \r\n");
      out.write("      //alert();\r\n");
      out.write("      form.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function create_hidden(name, val, form){\r\n");
      out.write("      input = document.createElement(\"input\");\r\n");
      out.write("      input.type = \"hidden\";\r\n");
      out.write("      input.name = name;\r\n");
      out.write("      input.value = val;\r\n");
      out.write("      form.append(input);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /porder/create.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /porder/create.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/porder/create.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /porder/create.jsp(175,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("shopping_cartVO");
      // /porder/create.jsp(175,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/porder/create.jsp(175,12) '${shopping_cartlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${shopping_cartlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("              <tr>\r\n");
            out.write("                <td style='text-align: left;'><img src=\"./sample.png\" style=\"width: 50px; height: 50px;\"></td>\r\n");
            out.write("                <td style='padding:0 20px; text-align: left;'>장바구니 번호 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopping_cartVO.shopping_cartno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td style='padding:0 20px; text-align: center;'>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopping_cartVO.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" 개</td>\r\n");
            out.write("                <td style='padding:0 20px; text-align: center;'>오늘 출고</td>\r\n");
            out.write("              </tr>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /porder/create.jsp(253,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("shopping_cartVO");
      // /porder/create.jsp(253,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/porder/create.jsp(253,6) '${shopping_cartlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${shopping_cartlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        porder_detailArr.push({\r\n");
            out.write("          'itemno':'");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopping_cartVO.itemno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("',\r\n");
            out.write("          'quantity':'");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopping_cartVO.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("',\r\n");
            out.write("          'item_price_sum':'1',\r\n");
            out.write("          'item_discount_sum':'1',\r\n");
            out.write("          'payment_price':'1'\r\n");
            out.write("          //'porder_detail_status':'1'\r\n");
            out.write("        });\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
